### ISSUE TITLE
No repository link on pypi.org, all links in README on pypi.org point to non-existent places on pypi.org

### ISSUE THREAD

**Issue by ssteinerx** [fabien-marty/jinja-tree#2]
I found jinja-tree on PyPi while searching for Jinja related tools.

I had to search on github to find this repository.  A link in the PyPi listing pointing to this repository would be helpful.

The links in the rendered README here on github work.

The ones on PyPi  point to the same relative locations but on pypi.org.  

Unfortunately, none of those locations on pypi.org actually exist so they all 404 out.

Looks like an interesting tool...now where was I?

**Comment by fabien-marty** [comment]
Hi Steve,

I'm glad you're interested in the tool.

Thanks for this issue. I uploaded the first version of "jinja-tree" to pypi... yesterday. So indeed, not everything is perfectly polished.

=> I'm going to fix this very soon
